### ISSUE TITLE
About query sampling

### ISSUE THREAD

**Issue by chenhbo** [mabaorui/NeuralPull-Pytorch#3]
Hi, there. Awesome work!

In the PyTorch version, I have a little confused about process_data part.

`
    POINT_NUM = pointcloud.shape[0] // 60
    POINT_NUM_GT = pointcloud.shape[0] // 60 * 60
    QUERY_EACH = 1000000//POINT_NUM_GT
`
Could I ask what the numbers 60 and 1000000 mean?  Why 60 and 1000000?
In the TensorFlow version, QUERY_EACH was clearly defined as 25, the same as the paper mentioned.

Thank you very much.

Look forward to your reply.

Best,
Frank

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest, 1000000 is the total number of sampled query points, and 60 is only a factor to control the gpu memory usage.  The reason is that if the point cloud is too large, it will take a long time for sampling 25 queries for each point, which is also not necessary, so we make it more adaptive by limit the total number of queries.

**Comment by chenhbo** [comment]
I see, thank you very much for your reply!
And thanks again for this nice work.

Sorry to bother you with another small question:
In the Gaussian distribution, how to choose the scale, and what effect does it have on the results? Make the sampling more robustness?

`scale = 0.25 * np.sqrt(POINT_NUM_GT / 20000)`

Also, in the TensorFlow version, I see the scale was chosen as 1.0 and 0.15, respectively.

Thank you for your patience！

**Comment by junshengzhou** [comment]
Hi,
As we mentioned in the README, the scale has a big influence on the performance of Neural-Pull. The reason is that if the queries are too far from the surface, the space near the surface can not convergent well, vice versa for the situation where the queries are too close to the surface. So it is important to test different scales for different dataset where the number of points and the complexity of geometries are quite different.
Same, different from the Tensorflow version where the scale is set to a fixed value, in the Pytorch version, we provide an adaptive solution as `scale = 0.25 * np.sqrt(POINT_NUM_GT / 20000)` to handle different densities of input point clouds, which is our empirical judgment. You can simply modify it to test different scales or the combination of them.

**Comment by chenhbo** [comment]
Great, I appreciate for your kind help, and thanks for this awesome work!
